app:
  host: 0.0.0.0
  port: 18084


log:
  level: INFO
  fileName: "./logs/app.log"
  maxSize: 10
  maxAge: 7
  maxBackups: 10
  comPress: false

dingtoken:
  tfwms: ""
  tfpos: "**************************"


#  jvm dump 配置
#  需要配置标签 currentValue: {{ $value }} jvm_dump: true 具体查看
jvm:
  # 是否开启dump操作,是指在容器内存达到85%小于90%时，触发jvm dump操作，默认不开启
  is_dump: true
  # 内存使用率: 执行dump时 内存使用率最大值和最小值 之所以有这个判断 是因为 有时候内存使用率过高 执行dump操作会导致pod重启 这个值根据实际情况 进行预留
  dump_min: 85
  dump_max: 90
  # 告警时间: 执行dump最大时间和最小时间 指的是当前时间距离发生告警是否超过24h并且小于28h
  dump_ts_min: 0
  dump_ts_max: 1

# 应用判断告警项时 标签名称
# 对应的是 Prometheus告警规则中自定义的labels名称 这里之所以抽出来，是为了方便自定义标签
labels:
  # 用于 定义触发该告警项时 导出对应pod jvm快照 这里等于是告警项中定义标签 jvm_dump="true"
  jvm_labels: "jvm_dump"
  # 用于 定义触发该告警项时 是否获取告警项的对应资源事件(目前只支持pod事件) 这里等于是告警项中定义标签 events="true"
  event_labels: "events"
